version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - restore_cache:
          # projectname can be anything, so long as it matches save_cache below.
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            pip3 install pipenv
            pipenv install -e .[dev] --skip-lock
            pipenv graph
      - save_cache:
          key: deps0-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.8/site-packages"
      """- run:
          name: Running tests
          # set COVERALLS_REPO_TOKEN=<...> in ENVIRONMENT variables in circleci
          command: |
            pipenv install coveralls --skip-lock
            pipenv run coverage run setup.py test"""
      - run:
          name: Coverage
          command: |
            pipenv run coverage report -i
            pipenv run coverage html -i
            pipenv run coveralls
      - store_test_results:
          path: htmlcov
      - store_artifacts:
          path: htmlcov
          destination: rapa